### ISSUE TITLE
SKR Pro

### ISSUE THREAD

**Issue by V1EngineeringInc** [jeffeb3/MarlinBuilder#15]
For the TFT not to freak out it is best to keep extruder = 1. With 6 drivers it is not an issue. Should we run it that way or figure out why the TFT freaks with an M22 code with E=0? 

Error M221 (feedrate setting). So maybe just remove the extruder, bed,  and feedrate buttons from the home screen to fix it, or maybe not. I can poke around a little further to see if I can figure that out.

**Comment by jeffeb3** [comment]
It seems like it would just be a metter of opening the second serial port on the rambo to get it to also work on the screen.

If that's the case, then fixing the screen may prove useful.

I don't like software tellibg me what to do (I've always had a bit of a problem with authority), so I would prefer to be able to do extruders=0 on any board.

I remember some problems with octoprint with extruders=0 too. It warns me about not having thermal protection enabled.

**Comment by V1EngineeringInc** [comment]
I see where I can remove the commands on the TFT side. Moving buttons is not so straight forward. I will have to spend some more time seems there are multiple layers to align and or remove. Images, and info, there is also the import/poling commands. At least from what I can figure out. 

I will mess around again. I think I will put up the image I currently have and get some out there to some brave early adopters/testers. That way we know exactly what to do with this auto version.

**Comment by jeffeb3** [comment]
Closing. I think this is resolved.
